version: "2"
linters:
  default: none
  enable: [errcheck, govet, ineffassign, staticcheck, unused]
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
formatters:
  enable: [gofmt]
