FROM alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
RUN apk add --no-cache libcrypto3=3.5.8-r0 libssl3=3.5.8-r0 \
    && addgroup -S -g 10003 secret-init && adduser -S -D -H -u 10003 -G secret-init secret-init \
    && mkdir -p /secrets && chown secret-init:secret-init /secrets
USER 10003:10003
